def test
    raise Exception("This is an exception message")
end

test()
